services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/app:rw
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: requirements.txt
          action: rebuild
        - path: compose.yaml
          action: rebuild
  
  # URL: postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-pw
      - POSTGRES_DB=timescaledb
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
volumes:
  timescaledb_data: