services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    # environment:
    #   - PORT=8002
    #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    depends_on:
      db_service:
        condition: service_healthy
    environment:
      - PYTHONPATH=/code
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: requirements.txt
          action: rebuild
        - path: compose.yaml
          action: rebuild
  
  # URL: postgresql+psycopg://time-user:time-pw@hostvalue:5432/timescaledb
  db_service:
    image: timescale/timescaledb:latest-pg17
    # env_file:
    #   - .env.compose
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # left = host, right = container
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timeuser -d timescaledb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=timeuser
      - POSTGRES_PASSWORD=timepw
      - POSTGRES_DB=timescaledb
volumes:
  timescaledb_data: