services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8002
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/app:rw
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: requirements.txt
          action: rebuild
        - path: compose.yaml
          action: rebuild
  db_service:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
volumes:
  timescaledb_data: